language: java
sudo: false
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.gradle/caches/"
install:
  - ./gradlew assemble
before_script:
  - echo -e "gradle.publish.key=$APIKEY\ngradle.publish.secret=$APISECRET" > gradle.properties
scipt:
  - ./gradlew jacocoTestReport build publish bintrayUpload
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/19d1516a0a3505ee7489
    on_success: change
    on_failure: always
    on_start: never



